### ISSUE TITLE
Enable Vulkan and ShaderTools in vcpkg

### ISSUE THREAD

**Issue by Luke-Filewalker** [mosra/magnum#485]
How can I install magnum with vcpkg and get vulkan working? 

Inside 
`vcpkg\packages\magnum_x64-windows\include\Magnum`
there is not even a vk folder like it is the case with the github repo.

**Comment by mosra** [comment]
Yeah, this still needs to be enabled :) The main part of the `Vk` library got merged only very recently and there's also `ShaderTools` that yren't there yet. I'm unfortunately not a Vcpkg user myself, so I have to delegate.

@Squareys, would you find some free time to enable the new stuff in vcpkg (and the plugins as well)? Thank you!

**Comment by mosra** [comment]
@Luke-Filewalker if you feel adventurous (plus a guideline for @Squareys later), in order to enable the new libraries it *hopefully* should be enough to edit [ports/magnum/CONTROL](https://github.com/microsoft/vcpkg/blob/master/ports/magnum/CONTROL) in your local vcpkg copy and add these lines:

```
Feature: shadertools
Description: ShaderTools library

Feature: vk
Description: Vk library
Build-Depends: vulkan

Feature: vk-info
Description: vk-info utility
Build-Depends: magnum[core,vk]

Feature: anyshaderconverter
Description: AnyShaderConverter plugin
Build-Depends: magnum[core,shadertools}

Feature: shaderconverter
Description: magnum-shaderconverter utility
Build-Depends: magnum[core,shadertools,anysceneconverter]
```

Then installing Vulkan and related tools should be a matter of `vcpkg install --head magnum[vk,vk-info,shadertools,shaderconverter]`. For the shadertools plugins it would then be a similar change in [ports/magnum-plugins/CONTROL](https://github.com/microsoft/vcpkg/blob/master/ports/magnum-plugins/CONTROL):

```
Feature: glslangshaderconverter
Description: GlslangShaderConverter plugin
Build-Depends: glslang, magnum[shadertools]

Feature: spirvtoolsshaderconverter
Description: SpirvToolsShaderConverter plugin
Build-Depends: spirv-tools, magnum[shadertools]
```

However, looking at the [vulkan portfile](https://github.com/microsoft/vcpkg/blob/master/ports/vulkan/portfile.cmake) it seems that depending on Vulkan isn't as straightforward as it used to be with GL, and because it involves some manual steps I'm afraid it won't be a good idea to enable it by default. Sigh.

- - -

The above is just an optimistic scenario. Based on our history with vcpkg things never went *that* smooth and it always involved some additional hair-pulling, but maybe it will "just work" this time :)

**Comment by Luke-Filewalker** [comment]
Unfortunately, an error occurred when re-building magnum during step
`-- Building x64-windows-dbg`

Nevertheless, thanks for the quick respond.
I am looking forward to the official update. :)

**Comment by mosra** [comment]
Yeah I suppose that's how it asks you to manually install Vulkan :sweat_smile: If you can show more of the log, I could maybe know what's up and how to fix it. The Vk library [should build correctly on Windows](https://magnum.graphics/build-status/), so I suppose the problem is somewhere else.

**Comment by Luke-Filewalker** [comment]
It was something different, here are the log files

`Starting package 2/2: magnum:x64-windows
Building package magnum[anyaudioimporter,anyimageconverter,anyimageimporter,anysceneconverter,anysceneimporter,anyshaderconverter,audio,core,debugtools,gl,meshtools,primitives,scenegraph,sdl2application,shaderconverter,shaders,shadertools,text,texturetools,trade,vk,vk-info]:x64-windows from HEAD...
-- Downloading https://api.github.com/repos/mosra/magnum/git/refs/heads/master...
-- Skipping hash check for C:/Users/User/Documents/Programming/vcpkg/downloads/temp/mosra-magnum-master.tar.gz.version.
-- Downloading https://github.com/mosra/magnum/archive/master.tar.gz...
-- Skipping hash check for C:/Users/User/Documents/Programming/vcpkg/downloads/temp/mosra-magnum-master.tar.gz.
-- Extracting source C:/Users/User/Documents/Programming/vcpkg/downloads/mosra-magnum-master.tar.gz
-- Applying patch 001-tools-path.patch
-- Applying patch 002-sdl-includes.patch
-- Using source at C:/Users/User/Documents/Programming/vcpkg/buildtrees/magnum/src/head/master-e300ab4d89.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: C:/Users/User/Documents/Programming/vcpkg/buildtrees/magnum/x64-windows-dbg
    See logs for more information:
      C:\Users\User\Documents\Programming\vcpkg\buildtrees\magnum\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/magnum/portfile.cmake:78 (vcpkg_install_cmake)
  scripts/ports.cmake:136 (include)


Error: Building package magnum:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: magnum:x64-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.`

**Comment by mosra** [comment]
Ok, we'll try to figure that out with @Squareys then :)

**Comment by pezcode** [comment]
Just gave it a try with @mosra's changes and it works fine for me, just had to remove corrade and install that with --head too, otherwise it would use the 2020.06 release and complain about missing `StringView`

**Comment by Squareys** [comment]
Done: https://github.com/microsoft/vcpkg/pull/15163

**Comment by mosra** [comment]
The PR is merged now, but one issue remains as it was discovered too late -- https://github.com/microsoft/vcpkg/blob/master/ports/magnum/magnumdeploy.ps1 doesn't take care of the new plugin interfaces (shaderconverters and sceneconverters), so the new plugin DLLs are not copied.

Keeping this open until that's resolved as well.

**Comment by Squareys** [comment]
@mosra I believe this can be closed now, as https://github.com/microsoft/vcpkg/pull/16245 is merged.

**Comment by mosra** [comment]
Yep! Closing as done.
